import type { Idea } from "@/components/ideas/types";

export const SAMPLE_IDEAS: Idea[] = [
  {
    id: "idea-1",
    title: "深夜のドライブで聴きたい曲",
    description: "夜のドライブシーンに合う洋楽・邦楽のプレイリストを紹介するショート動画。",
    genre: "音楽・プレイリスト",
    aiScore: 82,
    status: "approved",
    isDuplicate: false,
    createdAt: "2025-05-12",
  },
  {
    id: "idea-2",
    title: "毛穴を消すスキンケア3選",
    description: "毛穴の目立ちを軽減する市販スキンケアアイテムをビフォーアフターで紹介。",
    genre: "美容・スキンケア",
    aiScore: 76,
    status: "draft",
    isDuplicate: true,
    createdAt: "2025-05-14",
  },
  {
    id: "idea-3",
    title: "時短家電がマジで便利",
    description: "自動調理器や電動ケトルなど、時間を節約できる家電を実演レビュー。",
    genre: "ライフスタイル・家電",
    aiScore: 65,
    status: "draft",
    isDuplicate: false,
    createdAt: "2025-05-15",
  },
  {
    id: "idea-4",
    title: "レンジで作る爆速レシピ",
    description: "電子レンジのみで完成する5分レシピを紹介するシリーズ企画。",
    genre: "料理・時短レシピ",
    aiScore: 91,
    status: "approved",
    isDuplicate: false,
    createdAt: "2025-05-10",
  },
  {
    id: "idea-5",
    title: "夏に買うべき服TOP5",
    description: "夏シーズンにおすすめのファッションアイテムをランキング形式で紹介。",
    genre: "ファッション",
    aiScore: null,
    status: "draft",
    isDuplicate: false,
    createdAt: "2025-05-16",
  },
  {
    id: "idea-6",
    title: "沖縄旅行Vlog #1",
    description: "沖縄の観光スポットとグルメを巡る旅行Vlogシリーズの第1話。",
    genre: "旅行・Vlog",
    aiScore: 58,
    status: "rejected",
    isDuplicate: false,
    createdAt: "2025-05-08",
  },
  {
    id: "idea-7",
    title: "猫のかわいい瞬間集 #3",
    description: "SNSで話題になった猫の可愛い行動をまとめたコンピレーション動画。",
    genre: "ペット・猫",
    aiScore: 88,
    status: "approved",
    isDuplicate: true,
    createdAt: "2025-05-11",
  },
  {
    id: "idea-8",
    title: "集中力が上がる勉強法",
    description: "科学的根拠に基づいた集中力向上テクニックを分かりやすく解説。",
    genre: "学習・自己啓発",
    aiScore: 70,
    status: "draft",
    isDuplicate: false,
    createdAt: "2025-05-13",
  },
];
